### ISSUE TITLE
sway: missing wallpaper

### ISSUE THREAD

**Issue by dev-0x7C6** [MarkusVolk/meta-wayland#1]
Hi,

With default configuration there is missing background asset. Sway complains about missing `/usr/share/backgrounds/sway/Sway_Wallpaper_Blue_1920x1080.png` file.

Cheers,
Bartłomiej

**Comment by MarkusVolk** [comment]
The wallpapers get installed only, if PACKAGECONFIG  'default-wallpaper' is set. Should we install them by default?
That'll need 5MB additional Space

**Comment by dev-0x7C6** [comment]
Weston run out of box without errors. I think that sway should create same impression (with or without wallpaper).

Is there a way to change initial configuration to exclude wallpaper configuration if default-wallpaper isn't present? Anyway this is build flag. I think this should be fixed in sway since they know that wallpaper will be not installed after build and they're providing invalid configuration anyway.

**Comment by MarkusVolk** [comment]
in sway meson.options its like this:
`option('default-wallpaper', type: 'boolean', value: true, description: 'Install the default wallpaper.')`
The wallpapers get installed by default therefore no warning appears in the default configuration. But i agree, it would be nice,
if sway just wont complain about missing wallpapers if there is a flag to disable them.

**Comment by MarkusVolk** [comment]
Anyway, since the default is to install the wallpapers i possibly should also add that to PACKAGECONFIG in sway_git.bb.

If people really need to save that space they can do it either way. Its more or less a matter of taste if you want to to `PACKAGECONFIG_remove =` or `PACKAGECONFIG_append =`  from a bbappend.

**Comment by MarkusVolk** [comment]
[0001-config.in-dont-use-swaybg-by-default.zip](https://github.com/MarkusVolk/meta-wayland/files/6604292/0001-config.in-dont-use-swaybg-by-default.zip)
Or perhaps we should do it like this? Otherwise also swaybg should be made a mandatory RDEPEND

**Comment by MarkusVolk** [comment]
https://github.com/MarkusVolk/meta-wayland/commit/8044de610cac545b2ffe55b6f64eff6cb891fb5c
