### ISSUE TITLE
Can't build cage

### ISSUE THREAD

**Issue by JeanPhilippeLebel** [MarkusVolk/meta-wayland#2]
Hi!

I have a bunch of compilations error when trying to add Cage to my image. wlroots compiles fine. Poky is at master/main.

The first error is shown below

ypes/wlr_surface.h:1:2: error: #warning "wlr/types/wlr_surface.h has been deprecated and will be removed in the future. Use wlr/types/wlr_compositor.h and wlr/types/wlr_subcompositor.h." [-Werror=cpp]
|     1 | #warning "wlr/types/wlr_surface.h has been deprecated and will be removed in the future. Use wlr/types/wlr_compositor.h and wlr/types/wlr_subcompositor.h."
|       |  ^~~~~~~
| ../git/xdg_shell.c: In function 'popup_unconstrain':
| ../git/xdg_shell.c:75:38: error: too few arguments to function 'wlr_output_layout_get_box'
|    75 |         struct wlr_box *output_box = wlr_output_layout_get_box(output_layout, wlr_output);
|       |                                     

Thanks

**Comment by MarkusVolk** [comment]
Hi

In the meta-wayland master branch, wlroots is too up-to-date for cage. Actually also for phoc and wayfire, but these projects can build their own wlroots as submodules, unlike cage.

There is already a pull request for some of the needed changes, but there hasn't been much activity lately
https://github.com/Hjdskes/cage/pull/229

I have created the kirkstone branch directly before the wlroots update. Hopefully you'll be able to build cage using it

**Comment by JeanPhilippeLebel** [comment]
Using the Kirkstone branch does indeed fix the issue. Thanks.
