### ISSUE TITLE
Upstream libvarlink recipe to poky/meta-oe

### ISSUE THREAD

**Issue by adinath-mhatre** [MarkusVolk/meta-wayland#4]
Hi @MarkusVolk, I want use libvarlink recipe from this repo but currently I'm not using meta-wayland.
Is there any plan to upstream only libvarlink recipe to poky/meta-openembedded ?

**Comment by MarkusVolk** [comment]
Unfortunately not. I hardly use this recipe and had created it only for some tests. But everyone may feel free to simply take any recipe from my layers and propose at meta-openembedded. If it is accepted, I will delete it here.
